language: go
go:
  - "1.11.x"

jobs:
  include:
    - stage: "Test"
      name: "Standrad build process with vetting and tests"
      script: make
    - stage: "Docker"
      name: "Build a Docker image"
      script: make docker-build
env:
  - GO111MODULE=on