language: go
go:
  - "1.11.x"

jobs:
  include:
    - stage: "Test"
      name: "Vetting and unit tests"
      script: make test
    - stage: "Build"
      name: "Building a binary"
      script: make build
    - stage: "Build"
      name: "Building a Docker image"
      script: make docker-build
      
env:
  - GO111MODULE=on