language: go
go:
  - "1.11.x"

jobs:
  include:
    - stage: "Test"
      name: "Vetting and unit tests"
      script:
        - go get -u golang.org/x/lint/golint
        - make prepare
        - make test
    - stage: "Build"
      name: "Building binary"
      script: make build
    - stage: "Build"
      name: "Building Docker image"
      script: make docker-build
      
env:
  - GO111MODULE=on