global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
- job_name: 'item'
  static_configs:
  - targets: ['item:8080']

- job_name: 'jaeger'
  static_configs:
  - targets: ['jaeger:5778','jaeger:14268','jaeger:16686','jaeger:14271']

- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'grafana'
  static_configs:
  - targets: ['grafana:3000']



